# Generated by Django 5.1.6 on 2025-02-26 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_movie_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie',
            table=None,
        ),
    ]
