# Generated by Django 5.1.7 on 2025-03-09 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=300)),
                ('status', models.BooleanField(default=False)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
